2021-11-22 11:40:21,670 INFO    MainThread:5676 [wandb_setup.py:_flush():71] setting env: {}
2021-11-22 11:40:21,670 INFO    MainThread:5676 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-22 11:40:21,671 INFO    MainThread:5676 [wandb_init.py:_log_setup():357] Logging user logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211122_114021-3kgotziv\logs\debug.log
2021-11-22 11:40:21,671 INFO    MainThread:5676 [wandb_init.py:_log_setup():358] Logging internal logs to C:\Users\Spectra\Documents\GitHub\nd0821-c2-build-model-workflow-exercises\wandb\run-20211122_114021-3kgotziv\logs\debug-internal.log
2021-11-22 11:40:21,671 INFO    MainThread:5676 [wandb_init.py:init():390] calling init triggers
2021-11-22 11:40:21,671 INFO    MainThread:5676 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-22 11:40:21,671 INFO    MainThread:5676 [wandb_init.py:init():435] starting backend
2021-11-22 11:40:21,672 INFO    MainThread:5676 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-22 11:40:21,686 INFO    MainThread:5676 [backend.py:ensure_launched():199] starting backend process...
2021-11-22 11:40:21,781 INFO    MainThread:5676 [backend.py:ensure_launched():205] started backend process with pid: 14656
2021-11-22 11:40:21,781 INFO    MainThread:5676 [wandb_init.py:init():444] backend started and connected
2021-11-22 11:40:21,782 INFO    MainThread:5676 [wandb_init.py:init():503] updated telemetry
2021-11-22 11:40:21,875 INFO    MainThread:5676 [wandb_init.py:init():533] communicating current version
2021-11-22 11:40:23,607 INFO    MainThread:5676 [wandb_init.py:init():538] got version response 
2021-11-22 11:40:23,608 INFO    MainThread:5676 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-22 11:40:53,623 INFO    MainThread:5676 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-11-22 11:40:53,623 ERROR   MainThread:5676 [wandb_init.py:init():553] backend process timed out
2021-11-22 11:40:53,623 ERROR   MainThread:5676 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
